### ISSUE TITLE
make it so that you can shift click on a ladder to place above/below it depending on the half of the ladder you click on?

### ISSUE THREAD

**Issue by agentruru** [meeetj/Fabric-Better-Ladders#4]
handy for creating ladders from above a drop where you can't reach the underside of the ladder to place more

**Comment by meeetj** [comment]
sorry for not answering so long, thats definetly a nice idea!
although i won't implement it b/c for me this mod is supposed to be just a decorative building helper, changing as little vanilla behavior as possible. Also i wouldnt even know where to begin trying to implement that lol

there is [https://modrinth.com/mod/better-ladder-placements](url) for forge though, maybe ask them if they can replicate it for fabric?
