### ISSUE TITLE
Minor Bug: 3D and No-3D version are linked when ModMenu checks updates.

### ISSUE THREAD

**Issue by Nova-Katt** [meeetj/Fabric-Better-Ladders#5]
Very minor bug since it doesn't affect the gameplay whatsoever really.
But I noticed that due to the different versions of the mod, with and without 3D being linked together as a chain, ModMenu is telling me that there is an updated mod even when I run the latest version.
The reason for that is that I run the 3D version, and the version-history is:

- Better Ladders 0.0.2.1.20.1-No-3D-Model
- Better Ladders 0.0.2.1.20.1
- v0.0.1-1.19.x-No-3D-Model](https://modrinth.com/mod/better-ladders/version/0.0.1-1.19.x-No-3D-Model)
- 0.0.1-1.19.x

So when I run Better Ladders 0.0.2.1.20.1, which is the latest... it is also the 2nd latest version, with No-3D-Model being the absolute latest, therefor the Mods menu in Minecraft is constantly telling me that this mod has been updated, but the only way to get rid of that notification is to switch to the No-3D version.
They should be separated so that it follows 0.0.2.1.20.1 instead of 3d or no-3d.

**Comment by meeetj** [comment]
I removed the 3D version completely for the newest version, so the mod is separate from any texture pack difference.
If anyone wants a 3D model just use one of the many 3D ladder resource packs.
